---
  - name: Ensure iterm2 is installed
    homebrew_cask:
      name: iterm2

  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure graphical utils are installed
    homebrew_cask:
      name:
        - docker
        - font-source-code-pro
        - keybase
        - osxfuse
        - ngrok
        - visual-studio-code

  - name: Ensure console utils are installed
    homebrew:
      name:
        - ansible-lint
        - bat
        - exa
        - git
        - gnupg
        - jsonlint
        - hub
        - fzf
        - mosh
        - mtr
        - nmap
        - pinentry-mac
        - pwgen
        - siege
        - sshfs
        - telnet
        - ripgrep
        - yamllint


  - name: Ensure python and node version managers are installed
    homebrew:
      name:
        - pyenv
        - n
