---
  - name: Ensure my productivity tools are installed
    homebrew_cask:
      name:
        - 1password
        - alfred
        - bettertouchtool
        - bluetoothconnector
        - karabiner-elements
        - bartender
        - chromium
        - cleanmymac
        - choosy
        - iina
        - ilya-birman-typography-layout
        - loom
        - notion
        - permute
        - protonvpn
        - rescuetime
        - slack
        - skype
        - transmission
        - zoomus
        - yandex

  - name: Ensure my streaming tools are installed
    homebrew_cask:
      name:
        - obs
        - loopback
        - audio-hijack
        - pretzel

  - name: Recuce noise from the macos
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.systempreferences
        key: AttentionPrefBundleIDs
        value: 0
      - domain: com.apple.dock
        key: no-bouncing
        value: TRUE
